# Generated by Django 4.0.4 on 2022-05-17 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='name',
            new_name='manager',
        ),
        migrations.AlterField(
            model_name='account',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 15, 50, 7, 605047)),
        ),
    ]
